### Numpy - A Big List of Assignments to practice

- A learn-by-doing approach
- Solutions to every problem
- Ready to use code/solution

In [1]:
import numpy as np

#### Note
Remember that NumPy arrays have a **defined data type**. This means **you are not able to insert strings into an integer type array**. NumPy is mostly used with double-precision data types.

#### Create a 1-D numpy array and describe its properties

In [2]:
a=np.array([21,22,33])
a

array([21, 22, 33])

In [3]:
## np.shape: This is a tuple of integers indicating the size of the array in each dimension.
## For a matrix with n rows and m columns, shape will be (n,m). 
print(f"Shape of array a is: {a.shape}") ## a is a Rank 1 array (which is essentially a vector)

print(f"**Remember that Shape of array returns a: {type(a.shape)}**\n")


## np.dim: In NumPy dimensions are called axes. The length of the shape tuple is therefore the number of axes, ndim.
print(f"Dimension of array a is: {a.ndim}") ## 1-d array

## The total number of elements of the array. This is equal to the product of the elements of shape.
print(f"Number of elements of array a is: {a.size}") ## 1-d array


Shape of array a is: (3,)
**Remember that Shape of array returns a: <class 'tuple'>**

Dimension of array a is: 1
Number of elements of array a is: 3


#### Create a 2-D numpy array and describe its properties

In [4]:
b=np.array([[120,131,142],[135,154,15]])
b

array([[120, 131, 142],
       [135, 154,  15]])

In [5]:
print(f"Shape of array b is: {b.shape}")
print(f"Dimension of array b is: {b.ndim}") 
print(f"Dimension of array b is (calculated via shape property): {len(b.shape)}")
print(f"Number of elements of array b is: {b.size}") 

Shape of array b is: (2, 3)
Dimension of array b is: 2
Dimension of array b is (calculated via shape property): 2
Number of elements of array b is: 6


#### Check if an array is empty

In [6]:
# Using size property
empt = np.array([])
if empt.size == 0:
    print("Array is empty")
else:
    print("Array is not empty")

Array is empty


#### Create an array with zeros

In [7]:
c=np.zeros((2,2))
c

array([[0., 0.],
       [0., 0.]])

#### Create an array with ones

In [8]:
d=np.ones((2,3))
d

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Create a numpy array of size 10, filled with zeros

In [16]:
print(f"Option 1:{np.zeros(10)}") # recommmmended approach
print(f"Option 2:{np.array([0.0]*10)}")
lst=[]
for i in range(10):
    lst.append(0.0)
    
print(f"Option 3:{np.asarray(lst)}")   # np.asarray: Convert the input to an array

Option 1:[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Option 2:[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Option 3:[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an integer array of size 5, filled with zeros

In [19]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

#### Create a 2x3 floating-point array filled with 1s

In [20]:
np.ones((3, 3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Create an array filled with a linear sequence (Starting at 5, ending at 25, stepping by 3)

In [23]:
# (this is similar to the built-in range() function)
np.arange(5, 25, 3)

array([ 5,  8, 11, 14, 17, 20, 23])

#### Create an array of 20 values evenly spaced between 2 and 30

In [22]:
np.linspace(2, 30, 20)

array([ 2.        ,  3.47368421,  4.94736842,  6.42105263,  7.89473684,
        9.36842105, 10.84210526, 12.31578947, 13.78947368, 15.26315789,
       16.73684211, 18.21052632, 19.68421053, 21.15789474, 22.63157895,
       24.10526316, 25.57894737, 27.05263158, 28.52631579, 30.        ])