### The Ultimate Numpy Practice Workbook

- A learn-by-doing approach
- Solutions to every problem
- Ready to use code/solution

In [2]:
import numpy as np

### Notes
- Remember that NumPy arrays have a **defined data type**. This means that **you shall not able to insert strings into an integer type array**. 

- _The main difference between a numpy array and a python list is that np.arrays allow vectorized operations;a list on the other hand can't handle vectorized operations (by design)_.
    - A `vectorized operation` means that `a function gets applied to each element in the numpy array`.

**Let's look at an example**

In [62]:
lst = [i for i in range(5)] # list
arr = np.arange(5) # numpy array
print(f"List is lst:{lst}")
print(f"Array is arr:{arr}")

List is lst:[0, 1, 2, 3, 4]
Array is arr:[0 1 2 3 4]


**Now let's add `5` to each element of the list and array**

In [63]:
lst = [i+5 for i in lst]
arr = arr + 5
print(f"Updated List is lst:{lst}")
print(f"Updated Array is arr:{arr}")

Updated List is lst:[5, 6, 7, 8, 9]
Updated Array is arr:[5 6 7 8 9]


**Now let's multiply 5 to each element of the list and array**

In [64]:
lst = [i*5 for i in lst]
arr = arr * 5
print(f"Updated List is lst:{lst}")
print(f"Updated Array is arr:{arr}")

Updated List is lst:[25, 30, 35, 40, 45]
Updated Array is arr:[25 30 35 40 45]


**Observe what happens when we try to multiply a list with a number**

In [65]:
lst = lst * 5
print(lst)

[25, 30, 35, 40, 45, 25, 30, 35, 40, 45, 25, 30, 35, 40, 45, 25, 30, 35, 40, 45, 25, 30, 35, 40, 45]


As observed from abv 2 examples:
- The addition and mutiplication operations can be directly applied on the numpy array
- But the lst needs a loop to access each element and apply the relevant opertion

**This makes numpy way faster and efficient to work with as compared to list for vectorized operations**.

### Good to know methods

#### A. Copy:
- Just like python lists, if we make a reference to a numpy array, (using **a = b**), both variables refer to the same underlying array.  (sort of aliasing)

In [16]:
a = np.array([1,2,3])
print(a)
b = a
b[0] = 10
print(f"a is:{a}")
print(f"b is:{b}")

[1 2 3]
a is:[10  2  3]
b is:[10  2  3]


- As observed abv, changing `b` changes `a`.
- The correct way to make a **copy** is via `copy()` function. It doesn't need any argument.

In [17]:
a = np.array([1,2,3])
print(a)
b = a.copy()
b[0] = 10
print(f"a is:{a}")
print(f"b is:{b}")

[1 2 3]
a is:[1 2 3]
b is:[10  2  3]


#### B. Casting:
A numpy array of one datatype can be **cast** to another using `astype()`. The new datatype (to be casted to) is passed as an argument.

In [18]:
a = np.array([1,2,3])
print(f"a is:{a} and dtype of a is {a.dtype}")
a = a.astype(dtype = np.float32)
print(f"Now a is:{a} and dtype of a is {a.dtype}")

a is:[1 2 3] and dtype of a is int64
Now a is:[1. 2. 3.] and dtype of a is float32


#### C. Empty array

There are 2 ways we can create empty arrays using numpy:
1. Using **zeros()**
    > all values are initialized to 0
2. Using **empty()**
    > - all values are initialized to junk
   - so might be a little faster to np.zeros()

In [19]:
empt1 = np.zeros((2,2))
empt3 = np.empty((2,2), dtype=int)
print(f"Empty array via zeros():{empt1}")
print(f"Empty array via empty():{empt3}")

Empty array via zeros():[[0. 0.]
 [0. 0.]]
Empty array via empty():[[ 1152921504606846976 -4611677256458621887]
 [     140191500468226      703141453891216]]


#### D. NAN
If we want to emulate missing values within a numpy array, we can use np.nan
**Note**: np.nan doesn't work on arrays with **dtype=int**

**E.g**:-

In [20]:
print("nan with floats: ", np.array([np.nan,2.3,np.nan]))
print("nan with strings: ",np.array([np.nan,"Hi","Numpy"]))
print("nan with integers; this will throw error: ",np.array([np.nan, 1, 2], dtype=np.int32))


nan with floats:  [nan 2.3 nan]
nan with strings:  ['nan' 'Hi' 'Numpy']


ValueError: cannot convert float NaN to integer

### Solved Assigments

#### 1. Create a 1-D numpy array and describe its properties

In [21]:
a=np.array([21,22,33])
a

array([21, 22, 33])

In [22]:
## np.shape: This is a tuple of integers indicating the size of the array in each dimension.
## For a matrix with n rows and m columns, shape will be (n,m). 
print(f"Shape of array a is: {a.shape}") ## a is a Rank 1 array (which is essentially a vector)

print(f"**Remember that Shape of array returns a: {type(a.shape)}**\n")


## np.dim: In NumPy dimensions are called axes. The length of the shape tuple is therefore the number of axes, ndim.
print(f"Dimension of array a is: {a.ndim}") ## 1-d array

## np.size: The total number of elements of the array. This is equal to the product of the elements of shape.
print(f"Number of elements of array a is: {a.size}") ## 1-d array


Shape of array a is: (3,)
**Remember that Shape of array returns a: <class 'tuple'>**

Dimension of array a is: 1
Number of elements of array a is: 3


#### 2. Create a 2-D numpy array and describe its properties

In [23]:
b=np.array([[120,131,142],[135,154,15]])
b

array([[120, 131, 142],
       [135, 154,  15]])

In [24]:
print(f"Shape of array b is: {b.shape}")
print(f"Dimension of array b is: {b.ndim}") 
print(f"Dimension of array b is (calculated via shape property): {len(b.shape)}")
print(f"Number of elements of array b is: {b.size}") 

Shape of array b is: (2, 3)
Dimension of array b is: 2
Dimension of array b is (calculated via shape property): 2
Number of elements of array b is: 6


#### 3. Check if an array is empty

In [25]:
# Using size property
empt = np.array([])
if empt.size == 0:
    print("Array is empty")
else:
    print("Array is not empty")

Array is empty


#### 4. Create an array with zeros

In [26]:
c=np.zeros((2,2))
c

array([[0., 0.],
       [0., 0.]])

#### 5. Create an array with ones

In [27]:
d=np.ones((2,3))
d

array([[1., 1., 1.],
       [1., 1., 1.]])

#### 6. Create a numpy array of size 10, filled with zeros

In [34]:
print(f"Option 1:{np.zeros(10)}") # recommmmended approach
print(f"Option 2:{np.array([0.0]*10)}")
lst=[]
for i in range(10):
    lst.append(0.0)
    
print(f"Option 3:{np.asarray(lst)}")   # np.asarray: Convert the input to an array
print(f"Option 4:{np.array(lst)}")

Option 1:[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Option 2:[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Option 3:[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Option 4:[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 7. Create an integer array of size 5, filled with zeros

In [35]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

#### 8. Create a 2x3 floating-point array filled with 1s

In [83]:
np.ones((2, 3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 9. Create an array filled with a linear sequence (Starting at 5, ending at 26, stepping by 3)

In [84]:
# (this is similar to the built-in range() function)
np.arange(5, 27, 3)

array([ 5,  8, 11, 14, 17, 20, 23, 26])

#### 10. Create an array of regularly spaced numbers beginning at 10, ending with 18.4 using an increment of 0.6

In [37]:
np.arange(10,18.5,0.6)

array([10. , 10.6, 11.2, 11.8, 12.4, 13. , 13.6, 14.2, 14.8, 15.4, 16. ,
       16.6, 17.2, 17.8, 18.4])

#### 11. Create a numpy array with values ranging from 30 to 45 

In [38]:
np.arange(30,46)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

#### 12. Given a numpy array, create a new  array with the same shape and type as the given array, filled with ones.

In [44]:
g = np.arange(10).reshape(2,5) # e.g. given array
print(f"Given array:")
print(g)

n = np.ones_like(g)
print(f"New array with 1s similar to g ")
print(n)

Given array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
New array with 1s similar to g 
[[1 1 1 1 1]
 [1 1 1 1 1]]


#### 13. Given a numpy array, create a new array with the same shape  as the given array, filled with zeros. The type of new array should be float

In [45]:
g = np.arange(10).reshape(2,5) # e.g. given array
print(f"Given array:")
print(g)

n = np.zeros_like(g, dtype= np.float32)
print(f"New array with 0s similar to g ")
print(n)

Given array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
New array with 0s similar to g 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 14. Given a numpy array, create a new array with the same shape and type as the given array, filled with 10

In [37]:
# Assuming that g is the given array
print("Option 1:")
print(np.full(g.shape,10)) # np.full() takes the shape of the given array and the value to fill
print(f"Option 2:")
print(np.full_like(g,10))  # np.full_like() takes the the given array and the value to fill

Option 1:
[[10 10 10 10 10]
 [10 10 10 10 10]]
Option 2:
[[10 10 10 10 10]
 [10 10 10 10 10]]


**15. Given a numpy array, create a new array with the same shape and type as the given array, filled with nan**

In [93]:
# Assuming that g is the given array
print(np.full_like(g,np.nan))

[[-9223372036854775808 -9223372036854775808 -9223372036854775808
  -9223372036854775808 -9223372036854775808]
 [-9223372036854775808 -9223372036854775808 -9223372036854775808
  -9223372036854775808 -9223372036854775808]]


#### 16. Create a numpy matrix of 3*3 integers, filled with fives

In [39]:
np.full((3,3),5,dtype=int)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

#### 17. Create a 4*4 identity numpy matrix 

In [46]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### 18. Create a numpy array with numbers from 11 to 20

In [44]:
np.arange(11,21)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

#### 19. Create an array of 20 values evenly spaced between 2 and 30

In [22]:
np.linspace(2, 30, 20)

array([ 2.        ,  3.47368421,  4.94736842,  6.42105263,  7.89473684,
        9.36842105, 10.84210526, 12.31578947, 13.78947368, 15.26315789,
       16.73684211, 18.21052632, 19.68421053, 21.15789474, 22.63157895,
       24.10526316, 25.57894737, 27.05263158, 28.52631579, 30.        ])

**20. Solve for the below set of equations**

x + 2y + 4z = 7,
3x + 7y + 2z = −11,
2x + 3y + 3z = 1

In [9]:
P = np.array([[1,2,4],[3,7,2],[2,3,3]])
Q = np.array([7,-11,1])
# Px = Q
x = np.linalg.solve(P, Q)
print("The solution for x,y,z is: ",x)

The solution for x,y,z is:  [-1. -2.  3.]
